#8. Implemente um programa que na primeira linha faça um print perguntando o nome do usuário e, na linha 2, chame a função input() para capturar o valor do teclado e armazenar na memória do computador.
print("Qual é seu nome?")
nome = input()
print("Que nome legal!",nome,".")
print("Quantos anos você tem?")
idade = input()
print(idade,"? Que interessante.")
print("Quantos Kg você tem?")
quilos = input()
print(quilos,",ok.")
print("Qual é a sua altura?")
altura = input()
print("Hm, muito bem! Aqui está sua ficha")
print("Nome:",nome)
print("Idade:",idade)
print("Peso em Kg:",quilos)
print("Altura em m:",altura)
print("Clique na tecla Enter para obter a sua avaliação final.")
input()
print("Seus dados apontam que você está dentro do padrão de acordo com suas informações, Meus parabéns!")
